FROM ollama/ollama

WORKDIR /root/.ollama 

COPY ./ollama_files /root/.ollama

EXPOSE 11434

# Start the Ollama service and pull the necessary model
CMD ["sh", "-c", "ollama pull gemma:2b && ollama run gemma:2b"]
